### ISSUE TITLE
Handle the Edit on Github link on every page with a Content Filter

### ISSUE THREAD

**Issue by davidmsinch** [sinch/docs#9]
Right now, the HTML markup for the "Edit on Github" link is present and repeated on every Markdown content page. This represents a substantial amount of duplication to maintain in the future. 

To make this easier to manage, we can create a content filter that will append the link in the footer of every content page right before pushing its contents to the Readme API.

The new `footer` filter will use [Mustache](https://mustache.github.io) to render a small `.mustache` template file as the footer of every page and append it to the final content to push to Readme.

An example configuration for the filter:

``` yaml
filters:
  - footer:
      template: templates/footer.mustache
      baseUrl: https://github.com/sinch/docs/blob/master/
```
